title: PK notes
description: Rozwiązania zadań z egzaminu aktuarialnego.
theme: just-the-docs

url: https://www.linkedin.com/in/przemyslaw-kopycki/

# Makes Aux links open in a new tab.
aux_links_new_tab: true

markdown:
  kramdown

mermaid:
  version: "9.1.3"

sass:
  quiet_deps: true
