title: PK notes
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://just-the-docs.github.io

# Makes Aux links open in a new tab.
aux_links_new_tab: true

markdown:
  kramdown

mermaid:
  version: "9.1.3"